name: Markdown Lint
on: 
  push:
    branches:
      - master
      - main
    paths:
      - '**.md'
      - '**/.markdownlint.*'
      - '**/github/workflows/markdownlint.yml'
  pull_request:
    paths:
      - '**.md'
      - '**/.markdownlint.*'
      - '**/github/workflows/markdownlint.yml'
jobs:
  markdown:
    runs-on: ubuntu-latest
    container:
      image: node:15.14-alpine
    steps:
      - uses: actions/checkout@master
      - run: npm install markdownlint-cli@0.27.1
      - run: npm run lint:markdown