name: Create Release
on:
  workflow_dispatch: {}
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.semantic.outputs.release-version }}
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@v2
      - name: Test2
        working-directory: /usr/local/bin
        run: | 
          ls -a

      - name: Test
        working-directory: ./the/path/to/test
        run: | 
          touch kustomization.yaml
          kustomize edit set image flanksource/template-operator:10
          kustomize edit add resource deploy.yml
          kustomize build . > deploy1.yml
      - uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
