name: Create Release
on:
  workflow_dispatch: {}
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.13.6
    steps:
      - uses: actions/checkout@v2
      - name: Test
        working-directory: /usr/local/bin
        run: | 
          ls -a
          

  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.semantic.outputs.release-version }}
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@v2
      - name: Test
        working-directory: ./the/path/to/test
        run: | 
          echo foo
          kubectl --help
          kustomize --help
          ls -a

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: deploy.yml
      #     path: the/path/to/test/
          #       kustomize build the/path/to/test/ > temp.yaml
          # cat temp.yaml
      - uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
